# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GdBsvfpPL4iVI9EeRINQNHNFCA3kI_GP
"""

def insertion_sort(arr):
    n = len(arr)
    for i in range(1, n):
        key = arr[i]
        j = i - 1
        try:
            while j >= 0 and key < arr[j]:
                arr[j + 1] = arr[j]
                j -= 1
            arr[j + 1] = key
        except (TypeError, ValueError):
            print("Ошибка в данных. Пожалуйста, введите только числа.")
            return False
    return True

while True:
    input_data = input("Введите числа через пробел для сортировки (для завершения введите 'q'): ")

    if input_data.lower() == 'q':
        break

    data = input_data.split()
    try:
        data = [int(x) for x in data]
    except (ValueError, TypeError):
        print("Ошибка в данных. Пожалуйста, введите только числа.")
        continue

    if insertion_sort(data):
        print("Отсортированный список:", data)