# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GdBsvfpPL4iVI9EeRINQNHNFCA3kI_GP
"""

def bubble_sort(arr):
    n = len(arr)
    for i in range(n):
        for j in range(0, n - i - 1):
            try:
                if arr[j] > arr[j + 1]:
                    arr[j], arr[j + 1] = arr[j + 1], arr[j]
            except (TypeError, ValueError):
                print("Ошибка в данных. Пожалуйста, введите только числа.")
                return False
    return True

while True:
    input_data = input("Введите числа через пробел для сортировки (для завершения введите 'q'): ")

    if input_data.lower() == 'q':
        break

    data = input_data.split()
    try:
        data = [int(x) for x in data]
    except (ValueError, TypeError):
        print("Ошибка в данных. Пожалуйста, введите только числа.")
        continue

    if bubble_sort(data):
        print("Отсортированный список:", data)